matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: PACKAGE=i386-elf-gcc
    - os: osx
      osx_image: xcode7.3
      env: PACKAGE=i386-elf-gcc
    - os: osx
      osx_image: xcode8.3
      env: PACKAGE=i386-elf-gdb
    - os: osx
      osx_image: xcode7.3
      env: PACKAGE=i386-elf-gdb

before_install: brew update

install:
  - mkdir -p $(brew --repo)/Library/Taps/nativeos
  - ln -s $PWD $(brew --repo)/Library/Taps/nativeos/homebrew-i386-elf-toolchain
  - brew tap --repair

script:
  - brew install -v $PACKAGE
  - brew test $PACKAGE
